language: go
os:
  - linux
  - osx
sudo: false
go:
  - 1.x
  - 1.6.x
  - 1.7.x
  - master
matrix:
  include:
    - os: linux
      env: GOARCH=386
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service travis-ci
