language: go
os:
  - linux
  - osx
sudo: false
go:
  - 1.x
  - 1.5
  - 1.6
  - 1.7.x
  - tip
  - master
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service travis-ci
